In [1]:
import numpy as np
import ipyparallel as ipp
%matplotlib inline

In [2]:
c = ipp.Client()
c.ids

[0, 1, 2, 3]

In [3]:
c[1:3].apply_sync(lambda: "Hola clase de MCA")

C:\Users\carlo\Anaconda2\lib\site-packages\dateutil\parser.py:605: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif res.tzname and res.tzname in time.tzname:


['Hola clase de MCA', 'Hola clase de MCA']

In [4]:
c[:].map_sync(lambda x,y,z: x+y+z, range(10), range(10), range(10))
dview = c[:]

In [5]:
%%timeit
x = 2**13
for i in np.arange(int(x**0.5)+1)[2:]:
    x % i

The slowest run took 4318.71 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 17.5 µs per loop


In [26]:
all?


In [35]:
x = 2**13

In [36]:
def PrimeQA(x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:])

In [16]:
PrimeQA(2**7)

False

In [17]:
dview.apply_sync(PrimeQA, 2**7)

[False, False, False, False]

In [18]:
2**np.arange(7)

array([ 1,  2,  4,  8, 16, 32, 64])

In [19]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(25))

10 loops, best of 3: 32.3 ms per loop


In [37]:
%%timeit
for i in 2**np.arange(25):
    x%i

The slowest run took 5.69 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.6 µs per loop


In [21]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(25))

10 loops, best of 3: 32.4 ms per loop


In [22]:
def PrimeQB(x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(int(x**0.5)+1)[2:]]))

In [23]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(25))

10 loops, best of 3: 34.9 ms per loop


In [53]:
np.mod?

In [56]:
15 % 12 #aritmetica modular

3

In [24]:
np.mod(24,12)

0

In [25]:
np.mod(np.arange(24),12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [26]:
np.array([hora % 12 for hora in np.arange(24)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [27]:
def PrimeQC(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x, lista)
    return np.all(residuos)

In [28]:
[12 % i for i in np.arange(24)[2:]]

[0, 0, 0, 2, 0, 5, 4, 3, 2, 1, 0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]

In [29]:
dview.map_sync(PrimeQC, 2**np.arange(10))

[True, True, False, False, False, False, False, False, False, False]

In [30]:
dview.map_sync(PrimeQA, 2**np.arange(25))

[True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [31]:
for i in np.arange(12,24):
    print np.mod(np.arange(24), i)

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0  1  2  3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20  0  1  2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21  0  1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22  0]


In [46]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(10))

10 loops, best of 3: 34.1 ms per loop


In [47]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(10))

10 loops, best of 3: 33.4 ms per loop


In [48]:
%timeit dview.map_sync(PrimeQC, 2**np.arange(10))

10 loops, best of 3: 32.9 ms per loop


In [49]:
np.mod(12, np.arange(24)[2:])

array([ 0,  0,  0,  2,  0,  5,  4,  3,  2,  1,  0, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12])

In [50]:
%timeit np.mod(12, np.arange(24)[2:])

The slowest run took 40.59 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.82 µs per loop


In [51]:
%timeit [12 % i for i in np.arange(24)[2:]]

The slowest run took 8.74 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.97 µs per loop
